// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa43xhFT9tEItvCzuNhTabXGOY41wH4EU',
    appId: '1:839572270931:web:af7fc1156f287c38537ba6',
    messagingSenderId: '839572270931',
    projectId: 'ht5yt45y',
    authDomain: 'ht5yt45y.firebaseapp.com',
    storageBucket: 'ht5yt45y.appspot.com',
    measurementId: 'G-Y479WTV4FK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCBW3xfzabTAXDk0WgDd6SX3X_TPjuQ1U',
    appId: '1:839572270931:android:b1af24beaa84d8ac537ba6',
    messagingSenderId: '839572270931',
    projectId: 'ht5yt45y',
    storageBucket: 'ht5yt45y.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsZQ7f-XRoDeqnUqgmsYj9FYezLTPOFpY',
    appId: '1:839572270931:ios:512bcb1967c26a27537ba6',
    messagingSenderId: '839572270931',
    projectId: 'ht5yt45y',
    storageBucket: 'ht5yt45y.appspot.com',
    iosBundleId: 'com.example.taskrootallyai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsZQ7f-XRoDeqnUqgmsYj9FYezLTPOFpY',
    appId: '1:839572270931:ios:512bcb1967c26a27537ba6',
    messagingSenderId: '839572270931',
    projectId: 'ht5yt45y',
    storageBucket: 'ht5yt45y.appspot.com',
    iosBundleId: 'com.example.taskrootallyai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa43xhFT9tEItvCzuNhTabXGOY41wH4EU',
    appId: '1:839572270931:web:c0c8c5139c8e1c61537ba6',
    messagingSenderId: '839572270931',
    projectId: 'ht5yt45y',
    authDomain: 'ht5yt45y.firebaseapp.com',
    storageBucket: 'ht5yt45y.appspot.com',
    measurementId: 'G-ZEZE7YJ0NZ',
  );
}
